version: 0.1
phases:
  install:
    commands:
      - npm install
      - npm install -g serverless
  build:
    commands:
      - serverless deploy

artifacts:
  files:
    - target/**/*
    - serverless.yml
    - deploy.sh
