version: 0.1
phases:
  install:
    commands:
      - npm install
      - npm install -g serverless
  build:
    commands:
      - serverless package --package target/dev
      - serverless deploy --package /target/dev

artifacts:
  files:
    - target/**/*
    - serverless.yml
    - deploy.sh
