Resources:
  UserTetstTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.database.UserTestTable}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: 'email'
          AttributeType: 'S'
        - AttributeName: 'name'
          AttributeType: 's'
      KeySchema:
        - AttributeName: 'email'
          KeyType: 'HASH'
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

