Resources:
  UserTetstTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.database.UserTestTable}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: 'email'
          AttributeType: 'S'
        - AttributeName: 'name'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'email'
          KeyType: 'HASH'
        - AttributeName: 'name'
          KeyType: 'RANGE'
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

