Resources:
  PaymentStateGlobalTable:
    Type: AWS::DynamoDB::GlobalTable
    Condition: IsPrimaryRegion
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: ${self:custom.database.globalTableName}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: 'pk'
          AttributeType: 'S'
        - AttributeName: 'sk'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'pk'
          KeyType: 'HASH'
        - AttributeName: 'sk'
          KeyType: 'RANGE'
      SSESpecification:
        SSEEnabled: true
        SSEType: 'KMS'
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Replicas:
        - Region: ${self:custom.primaryRegion}
          SSESpecification:
            KMSMasterKeyId: ${self:custom.database.primaryKmsKey}
          Tags:
            - Key: Automation
              Value: 'true'
            - Key: team
              Value: ${self:provider.tags.team}
            - Key: env
              Value: ${self:provider.tags.ENV}
            - Key: backup
              Value: 'on'
        - Region: ${self:custom.secondaryRegion}
          SSESpecification:
            KMSMasterKeyId: ${self:custom.database.secondaryKmsKey}
          Tags:
            - Key: Automation
              Value: 'true'
            - Key: team
              Value: ${self:provider.tags.team}
            - Key: env
              Value: ${self:provider.tags.ENV}
            - Key: backup
              Value: 'on'
  UserTetstTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.database.UserTestTable}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: 'email'
          AttributeType: 'S'
        - AttributeName: 'name'
          AttributeType: 's'
      KeySchema:
        - AttributeName: 'email'
          KeyType: 'HASH'
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

